apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-nfs
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: truenas-nfs
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: truenas-nfs-values
      namespace: truenas-nfs
