apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-nfs
  namespace: truenas-nfs
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: truenas-nfs-values
    - kind: Secret
      name: truenas-nfs-secrets
