apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - namespace.yaml

configMapGenerator:
  - name: truenas-nfs-values
    files:
      - values.yaml
