apiVersion: v1
kind: Secret
metadata:
  name: truenas-nfs-secrets
  namespace: truenas-nfs
stringData:
  apiKey: ENC[AES256_GCM,data:Ra4CIL491YUPiyhsJal7tvis86l+KSL2tvbWQ8tNxFJShTCn+NdrhnT06T9ZSN3WIWmBtL7YJ00dpkZ3WuYYfEcA,iv:7K8727We3sDUsTUB3ee0qwmiUoohkI0JN93arAhcTR4=,tag:33svNtgxAjXjMdI42w2Vyg==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQd2szSjhyNm1aRkdsUXBG
        NStndlRvQ1QxcWdQaVhOWXdqWjFmdkFUTlZrCjZrbFErbTdlK1JReHdhRFlMYmlz
        ZGJ5NkFTSWR0alczU09saUs3RlRudUkKLS0tIDZncHZuaDZPTTlYVEtXRTd4cmVh
        NHIzbnBuWjdYSC94V1lmSVBuSCtGNjgKYz/RdWCU+fzug9ASnUmI6PDoS9bLkhed
        3XBLhZQsew8S2/YKIb+3iJXkEnrffwy1QqCHoVxb8MVC63xuIskovQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T22:27:08Z"
  mac: ENC[AES256_GCM,data:9oBIskJR3WrumoZlUIlfqDHMRKxUCjyX2h0RceFwcJZvQu1gF1Yc5WWVnhewX9qlCTqG19M2i6RfM/9VKE4nRf5uLYsYzmQF9NyTTuTlYu1ZZ4ZcdQvgu1i0aIXjH9QR2QwZmmO6Gn1p3c6UdTaMauM6zP66gABjXkqDlk1z6Gw=,iv:AXNrHMJolueawoHmC1SHySb2RU9uobPrSbx5ejE+k8U=,tag:6I4SVHnx8c8gvwsnyH/9vg==,type:str]
  encrypted_regex: ^(data|stringData|apiKey|password|secret|token)$
  version: 3.11.0
