apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: trust-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 0.20.3
  values:
    app:
      trust:
        namespace: cert-manager
    replicaCount: 1
    crds:
      enabled: true
      keep: true
