apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: redis-operator-system
spec:
  interval: 15m
  chart:
    spec:
      chart: redis-operator
      sourceRef:
        kind: HelmRepository
        name: redis-operator
        namespace: flux-system
