apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-iscsi
  namespace: truenas-iscsi
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    createNamespace: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: truenas-iscsi-values
