apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: databases
spec:
  interval: 15m

  chart:
    spec:
      chart: cluster
      version: "0.5.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    # -----------------------------------------------------------------------------
    # Basic chart identity
    # -----------------------------------------------------------------------------
    nameOverride: "postgres"
    namespaceOverride: "databases"

    # -----------------------------------------------------------------------------
    # Database type and version
    # -----------------------------------------------------------------------------
    type: postgresql

    version:
      postgresql: "18"

    # -----------------------------------------------------------------------------
    # Mode of operation
    # -----------------------------------------------------------------------------
    mode: standalone

    # -----------------------------------------------------------------------------
    # PostgreSQL cluster configuration
    # -----------------------------------------------------------------------------
    cluster:
      instances: 1

      storage:
        size: 50Gi
        storageClass: truenas-fast-iscsi

      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 2Gi

      enableSuperuserAccess: true
      superuserSecret: "pg-superuser"

      postgresql:
        parameters:
          max_connections: "200"
          shared_buffers: "256MB"
          work_mem: "16MB"
          maintenance_work_mem: "128MB"
          wal_compression: "on"

      roles:
        - name: immich
          ensure: present
          login: true
          passwordSecret:
            name: immich-db-credentials

    # -----------------------------------------------------------------------------
    # Declarative database management
    # -----------------------------------------------------------------------------
    databases:
      - name: immich
        owner: immich
        extensions:
          - name: vector
          - name: cube
          - name: earthdistance

    # -----------------------------------------------------------------------------
    # Backups
    # -----------------------------------------------------------------------------
    backups:
      enabled: false

