apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: ot-container
        namespace: flux-system

  values:
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        cpu: 100m
        memory: 1000Mi
    nodeSelector:
      worker: "true"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: truenas-fast-iscsi
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
