apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-vip
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-vip
      version: "0.9.2"
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: flux-system
  values:
    config:
      address: 192.168.10.50

    env:
      cp_enable: "true"
      svc_enable: "false"
      # Control plane load balancing
      lb_enable: "false"
      vip_leaderelection: "true"
