apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-vip
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-vip-cloud-provider
      version: "0.2.9"
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: flux-system
  values:
    cm:
      data:
        range-global: 192.168.20.80-192.168.20.120

    # only reconcile normal LoadBalancer services (default)
    enableloadbalancerClass: false

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
